# Generated by Django 4.1 on 2022-11-08 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_alumni_profile_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('discipline', models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('Math', 'Math'), ('URP', 'URP'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Stat', 'Stat'), ('Pharmacy', 'Pharmacy'), ('BGE', 'BGE'), ('FWT', 'FWT'), ('FMRT', 'FMRT'), ('Agrotechnology', 'Agrotechnology'), ('ES', 'ES'), ('SWE', 'SWE'), ('BAD', 'BAD'), ('HRM', 'HRM'), ('DP', 'DP'), ('PM', 'PM'), ('DS', 'DS'), ('History', 'History'), ('English', 'English'), ('Bangla', 'Bangla'), ('IER', 'IER'), ('Sculpture', 'Sculpture'), ('Econ', 'Econ'), ('Sociology', 'Sociology'), ('MCJ', 'MCJ'), ('Law', 'Law')], max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('present_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumni_profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_events.event')),
            ],
        ),
    ]
