# Generated by Django 4.1 on 2022-09-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni_profile',
            old_name='prmanent_address',
            new_name='parmanent_address',
        ),
    ]
