# Generated by Django 4.1 on 2022-09-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_prmanent_address_alumni_profile_parmanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='job_position',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='job_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
