# Generated by Django 4.1 on 2022-11-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_alumni_profile_job_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='certificate',
            field=models.FileField(upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='image',
            field=models.FileField(upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
