# Generated by Django 4.1 on 2022-11-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_alumni_profile_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='higher_study',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
