# Generated by Django 4.1 on 2022-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_alumni_profile_higher_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
